' Gambas module file

Public Const DebugMode As Boolean = True

Public Conf As Settings
Public UIN As String
Public Password As String
Public Protocol As String
Public LocalPath As String
Public Const ConfigDefault As String = ""
"\"use strict\";module.exports={general:{platform:PROTOCOL,log_level:\"info\",use_cqhttp_notice:false,host:\"127.0.0.1\",port:5700,use_http:true,use_ws:false,access_token:\"\",secret:\"\",post_timeout:30,post_message_format:\"array\",enable_cors:false,enable_heartbeat:false,heartbeat_interval:15000,rate_limit_interval:500,event_filter:\"\",post_url:[\"http://127.0.0.1:5580\",],ws_reverse_url:[],ws_reverse_reconnect_interval:3000,ws_reverse_reconnect_on_code_1000:true,},};"
Public OutputCache As String
Public OutputCacheEnabled As Boolean = False
