' Gambas module file

Public CurSession As String = ""
Public SessionList As New Collection
Public Sessions As New Collection
Public Nickname As String 

Public Sub CQApi(Endpoint As String, Optional Params As String[] = []) As Variant
    Dim url As String, retval As String
    URL = "http://127.0.0.1:5700/" & endpoint & "?" & Params.Join("&")
    retval = http.Get(url)
    Return JSON.Decode(retval)["data"]
End

Public Function GroupPic(GroupID As String) As String
    Dim FilePath As String
    FilePath = g.localpath & "/fakeqqdata/group_images/" & groupid & ".jpg"
    If Not Exist(filepath) Then 
        Exec ["curl", "https://p.qlogo.cn/gh/" & GroupID & "/" & GroupID & "/100", "-o", FilePath] Wait
    Endif 
    Return filepath
End

Public Function UserPic(UserID As String) As String
    Dim FilePath As String
    FilePath = g.localpath & "/fakeqqdata/user_images/" & userid & ".jpg"
    If Not Exist(filepath) Then 
        Exec ["curl", "https://q1.qlogo.cn/g?b=qq&nk=" & userid & "&s=100", "-o", FilePath] Wait
    Endif 
    Return filepath
End

Public Function CQPic(sUrl As String) As String
    Dim FilePath As String
    FilePath = g.localpath & "/fakeqqdata/cq_images/" & Base64$(Replace(Crypt.MD5(sUrl, "fakeqpic"), "", "$1$fakeqpic$")) & ".jpg"
    If Not Exist(filepath) Then 
        Exec ["curl", surl, "-o", FilePath] Wait
    Endif 
    Return filepath
End

Public Function PrintMessage(Message As Variant) As String
    '消息json到richtext(html)
    'Print JSON.Encode(message)
    Dim Node As Variant, RetVal As String = "<p>"
    If Message["sender"]["card"] = "" Then 
        retval &= Message["sender"]["card"] & "："
    Else 
        retval &= Message["sender"]["nickname"] & "："
    Endif
    For Each node In Message["message"]
        Select Case node["type"]
            Case "text"
                retval &= node["data"]["text"]
            Case "at"
                retval &= "<b>" & node["data"]["text"] & "</b> "
            Case "face"
                retval &= "<img src=\"file://" & g.localpath & "/face/" & Format$(node["data"]["id"], "000") & "\" width=\"20\" height=\"20\" >"
            Case "image"
                'retval &= "<img src=\"" & m.cqpic(node["data"]["url"]) & "\" width=\"32\" >"
                retval &= "[图片]"
            Case "video"
                retval &= "[视频]"
            Case Else 
                retval &= JSON.Encode(node)
        End Select
    Next
    retval &= "</p>"
    Return retval
End
